docs/requirements.md

The milestone’s target is to be able to demonstrate the automatic provisioning
of a Storage Tenant to a VMware Cloud Director tenant organizations using
vCloud Director UI.

documentation: S3C-3770 Define milestone 1

---

docs/milestone-1-requirements.md
docs/milestone-2-requirements.md

added milestone 2 definition and reorganized the docs/ folder.

documentation: S3C-4012 Add milestone 2 requirements

---

build.gradle
osis-app/build.gradle
osis-core/build.gradle
osis-core/src/main/java/com/scality/osis/ScalityAppEnv.java
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/main/java/com/scality/osis/configuration/ScalityRestConfig.java
osis-core/src/main/java/com/scality/osis/security/basic/ScalityBasicAuthentication.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
pmd-rules.xml
pmd.gradle
src/main/java/com/scality/osis/Application.java
vault-admin-client/build.gradle

* Adding necessary Scality specific implementation classes by extending or replacing vmware classes
* Modifying application.properties using original vmware suggested properties for Vault and App info

feature: S3C-3525 Create Tenant-2

---

build.gradle
eve/workers/build/pod.yaml
eve/workers/docker/pod.yaml
pmd-rules.xml
pmd.gradle
vault-admin-client/build.gradle
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdminBuilder.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/ErrorUtils.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultServiceException.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/VaultAdminBuilderTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java
vault-admin-client/src/test/resources/vaultadmin.properties

* VaultAdmin is the administrator service class with implementations to interact with vault for all iam, account management and access control calls.
* BaseTest class uses mockito to mock vaultclient methods

feature: Create Tenant-3

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/resources/s3capabilities.json

Explanation: Using `S3Capabilities.json` provided with the Vmware OSE original stub for the getS3Capabilities() API

feature:S3C-3547 getS3Capabilities() default capabilities

---

build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/ScalityAppEnvTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java
pmd-rules.xml
pmd.gradle
vault-admin-client/build.gradle
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/ExternalServiceFactory.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

Changes:
* Moved all external service calls to a Factory class
* VaultAdmin changes with ListAccounts API
* Fix CreateTenant HttpStatus for errors. CreateTenant should allow only 400 HTTP status for errors.
* Modify helper method signature

feature:S3C-3527 list tenants-1

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java

Logic:
Query Tenants: Same list tenants behavior except filterKey in the ListAccountsRequestDTO

feature: S3C-3526 Query Tenants

---

eve/main.yml

Adding Docker release stage for production tag on eve

feature:S3C-3526 Adding Docker prod tag release stage

---

build.gradle
src/main/resources/application.properties
vault-admin-client/build.gradle
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

Description:
This code is to add a common code to get an `IAM client` for all OSIS APIs

feature:S3C-4094 getIAMClient() for all OSIS APIs

---

README.md

Description:
Updating docker run command with SELinux Read-only volume

documentation:S3C-4359 Update milestone1 validation with SELinux

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
src/main/resources/application.properties

1.  Implement CreateS3Credentials and Test Cases
2. Adding extra logs

feature:S3C-3540 Implement CreateS3Credentials and Test Cases

---

docs/api-compatibility-matrix.md
docs/milestone-1.md

API compatibility matrix for OSIS.
This will help POs plan the next milestone and also help devs prioritize development.

documentation: S3C-4371-api-compatibility-matrix

---

docs/api-compatibility-matrix.md
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/main/java/com/scality/osis/utils/ScalityUtils.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityUtilsTest.java

Implemented query s3 credentials for only filters `tenant_id`, `user_id`, `access_key`

Feature: OSIS-6 Query credentials

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java

Description: 
1. Detach User policy attached with user 
2. Delete IAM user

feature:OSIS-23 implement Delete User

---

osis-app/src/main/java/com/scality/osis/resource/ScalityOsisController.java
osis-core/src/main/java/com/scality/osis/model/ScalityOsisCaps.java
osis-core/src/main/java/com/scality/osis/model/ScalityOsisConstants.java
osis-core/src/main/java/com/scality/osis/resource/ScalityOsisCapsManager.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java

Description:
Moved all Stub code to Scality package to make not implemented apis list configurable
ref: https://developer.vmware.com/apis/1034#/info/getInfo

feature:OSIS-25 Making `getInformation` API `NotImplemented` configurable

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java

Description:
1. Update User's access keys status
2. Update get User/ list users behavior when access keys are inactive

feature:OSIS-24 Update User

---

build.gradle
docs/api-compatibility-matrix.md
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTenantTests.java
vault-admin-client/build.gradle
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

Description:
1. Update Account's customAttributes
Design ref: https://github.com/scality/osis/blob/development/1.0/Design.md#update-tenant

feature:OSIS-22 Update Tenant

---

build.gradle
osis-app/build.gradle
osis-core/build.gradle
vault-admin-client/build.gradle

Updates OSIS version from SNAPSHOT to real supported version.
Documentation: https://github.com/scality/osis/blob/development/1.0/docs/RELEASE.md#release-process

feature: OSIS-47-update-version-0.4.0

---

build.gradle
osis-app/build.gradle
osis-core/build.gradle
vault-admin-client/build.gradle

feature: OSIS-56-release-v-1.0.0

---

.github/workflows/test-and-build.yml

We already have a build action.
Changing this to test the wrapper instead.

bugfix: OSIS-69-fix-gradle-wrapper-command

---

docs/api-compatibility-matrix.md
osis-core/src/main/java/com/scality/osis/model/ScalityOsisConstants.java

- updated support matrix
- updated getInfo not implemented API list
note to reviewers: 
- This PR will be merged post https://github.com/scality/osis/pull/105 is merged.
- I will delete the 3rd commit before merging, I need https://github.com/scality/osis/pull/105 in for the same first.

docs: OSIS-89-update-support-matrix

---

build.gradle
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

Release v1.2.0
Changelog: https://scality.atlassian.net/projects/OSIS/versions/27596/tab/release-report-all-issues

feature: OSIS-90-release-osis-v1.2.0

---

build.gradle
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

bumping version to 1.4.0
Docker pull command: `docker pull registry.scality.com/osis/osis:1.3.0`

feature: OSIS-94-bump-osis-to-1.4.0

---

build.gradle

Upgrade Spring boot to 2.3.0.RELEASE

Improvement/osis 102 upgrade spring boot v2.2.5 v2.3

---

build.gradle

upgrade Spring boot to version 2.4.0
The application does not start correctly because of Java version incompatibility

Improvement/osis 103 upgrade spring boot v2.3 v2.4

---

build.gradle
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/main/java/com/scality/osis/resource/OsisJackson2ObjectMapperBuilderCustomizer.java
osis-core/src/main/java/com/scality/osis/service/impl/AsyncScalityOsisService.java
osis-core/src/test/java/com/scality/osis/ScalityAppEnvTest.java
osis-core/src/test/java/com/scality/osis/redis/service/ScalityRedisRepositoryTest.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
src/main/java/com/scality/osis/Application.java
storage-platform-clients/src/main/java/com/scality/osis/security/crypto/AES256GCM.java
storage-platform-clients/src/main/java/com/scality/osis/vaultadmin/utils/VaultAdminEnv.java
storage-platform-clients/src/test/java/com/scality/osis/security/utils/CipherFactoryTest.java
storage-platform-clients/src/test/java/com/scality/osis/vaultadmin/utils/VaultAdminEnvTest.java

Spring boot upgrade from 2.4.0 to 2.5.0
The application starts, no issues with Java compatibility

Improvement/osis 104 upgrade spring boot 2.4.0 2.5.0

---

Design.md

TAD design doc: https://scality.atlassian.net/wiki/spaces/OS/pages/2009366559/OSIS+getUsage+API+design+read+metrics+from+Utapi

documentation: S3C-7048-Osis-getUsage-design

---

build.gradle
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/main/java/com/scality/osis/resource/ScalityOsisCapsManager.java
osis-core/src/main/java/com/scality/osis/security/config/ScalityOsisBasicWebSecurityConfigurerAdapter.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
src/main/java/com/scality/osis/SpringfoxBug.java
src/main/resources/application.properties

Improvement/osis 105 upgrade spring boot 2.5.0 2.6.0

---

build.gradle
osis-core/src/main/java/com/scality/osis/security/config/OsisJwtWebSecurityConfigurerAdapter.java

A cycle in dependencies occurred when `security.jwt.enabled` was set to true

OSIS-129 use shared AuthenticationManager

---

osis-app/src/main/java/com/scality/osis/resource/ScalityOsisController.java
osis-core/src/main/java/com/scality/osis/model/Information.java
osis-core/src/main/java/com/scality/osis/model/OsisBucketMeta.java
osis-core/src/main/java/com/scality/osis/model/OsisError.java
osis-core/src/main/java/com/scality/osis/model/OsisS3Credential.java
osis-core/src/main/java/com/scality/osis/model/OsisTenant.java
osis-core/src/main/java/com/scality/osis/model/OsisUsage.java
osis-core/src/main/java/com/scality/osis/model/OsisUser.java
osis-core/src/main/java/com/scality/osis/model/PageInfo.java
osis-core/src/main/java/com/scality/osis/security/config/OsisJwtWebSecurityConfigurerAdapter.java
osis-core/src/main/java/com/scality/osis/security/config/ScalityOsisBasicWebSecurityConfigurerAdapter.java
osis-core/src/main/java/com/scality/osis/security/jwt/AuthConstants.java

upgrade deprecated openapi annotation required which is replaced by requiredMode

OSIS-132 upgrade deprecated openapi annotation required

---

build.gradle
osis-core/src/main/java/com/scality/osis/App.java

v2.1.0 compatible with VCD object storage extension 2.2.0.1

OSIS-141 bump-OSIS-to-v2.1.0

---

storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/GenericRequestMarshaller.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/GenericRequestProtocolMarshaller.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/GenericResponseJsonUnmarshaller.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/ListMetricsRequestDTO.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/ListMetricsRequestMarshaller.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/dto/MetricsData.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/services/BaseServicesClient.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/services/UtapiService.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/services/UtapiServiceClient.java
storage-platform-clients/src/main/java/com/scality/osis/utapiclient/utils/UtapiClientException.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/dto/GenericRequestMarshallerTest.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/dto/ListMetricsRequestDTOTest.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/dto/ListMetricsRequestMarshallerTest.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/dto/ListMetricsResponseJsonUnmarshallerTest.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/dto/MetricsDataTest.java
storage-platform-clients/src/test/java/com/scality/osis/utapiclient/services/UtapiServiceTest.java

implement utapi client to invoke utapi services(ex. ListMetrics)

Feature/osis 113 implement utapi client 
