scality/osis

jacoco.gradle
osis-core/src/main/java/com/scality/osis/configuration/ScalityRestConfig.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/ScalityAppEnvTest.java
osis-core/src/test/java/com/scality/osis/configuration/ScalityRestConfigTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

- createTenant() in ScalityOsisService uses VaultAdmin class to create an account on Vault.
- ModelConverter class has the functionality to transform account response to tenant response and vice versa
- Implemented unit test cases for Create Tenant and various helper methods using mockito and Junit

feature: Create Tenant-5

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java

Logic: getProviderConsoleURL() implemented from ScalityAppEnv.getConsoleEndpoint() which is set by Environment variable "osis.scality.console.endpoint"

feature: S3C-3545 Implement getProviderConsoleURL API

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java

Explanation: getOsisUsage() API with no usage data

feature:S3C-3551 getOsisUsage() API w/ no usage data

---

build.gradle
pmd-rules.xml
src/main/resources/application.properties
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/ExternalServiceFactory.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/cache/Cache.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/cache/CacheConstants.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/cache/CacheFactory.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/cache/CacheImpl.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/utils/ErrorUtils.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/utils/VaultAdminEnv.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/cache/CacheFactoryTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/cache/CacheImplTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/utils/VaultAdminEnvTest.java

Description:
* Implemented a thread-safe LRU cache with expiration time for each entry
* Created a Cache Factory that produces the Cache for each vault service
* cache properties can be loaded from environment variables i.e.,`application.properties`

feature:S3C-3527 [List Tenants] Implement in-memory cache for vault calls

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java
pmd-rules.xml
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/cache/CacheFactory.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/utils/VaultAdminEnvTest.java

Description:
* Implements List Tenants API using marker cache
* Compute Marker for the given offset from cache or by calling Vault list accounts
* Convert request and response from OSIS List Tenants to and from Vault List Accounts format
* Mock Vault List Accounts responses including marker scenarios
* Mock Vault responses for List Tenants calls

feature:S3C-3527 [List Tenants] Implementation and Unit Tests

---

Dockerfile

All CI builds are failing due to inconsistent Gradle version during code build and docker build

feature:S3C-4200 Correcting the Gradle image in docker build

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

Implemented `getCredentials` on `ScalityOsisService.java` to be used by all OSIS IAM flows. This method
* transforms `accountID` and prepares `AssumeRoleRequest`
* calls Vault with prepared `AssumeRoleRequest`

feature:S3C-4200 Assume role backbeat API Integration - 2

---

osis-core/src/main/java/com/scality/osis/ScalityAppEnv.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
src/main/resources/application.properties
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/BaseTest.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

Integrated Vault generateAccountAccessKey() during OSIS create Tenant to start the `Setup AssumeRole` subroutine

feature:S3C-4094 create tenant generateAccountAccessKey()

---

osis-core/src/main/java/com/scality/osis/ScalityAppEnv.java
osis-core/src/main/java/com/scality/osis/configuration/ScalityRestConfig.java
osis-core/src/main/java/com/scality/osis/service/impl/AsyncScalityOsisService.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/ScalityAppEnvTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java
pmd-rules.xml
src/main/java/com/scality/osis/Application.java
src/main/resources/application.properties
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultServiceException.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/utils/ErrorUtils.java
vault-admin-client/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

This PR is about implementing an asynchronous `setupAssumeRole` subroutine, after `create-account`, that prepares an account to be used by `assumeRoleBackbeat` during user flows (IAM).
ref: https://github.com/scality/vmware-ose-scality/blob/c1cc56602b590be96bfda10223fd7da94132b909/Design.md#setupassumerole-subroutine
* `setupAssumeRole` subroutine LOGIC:
1 Call `generateAccountAccessKey` with `durationSeconds` to generate temp creds
2 Call IAM `createRole` for `OSIS` super admin role with `assumerole` policy
3 Call IAM `createPolicy` to create admin policy with full IAM access
4 Call IAM `attachRolePolicy` to attach `OSIS` role with admin policy
5 Call `deleteAccessKey` to delete the access key for the account
* Async logic:
* Enabled Spring Async functionality
* Moved `setupAssumeRole()` …

feature:S3C-4094 Implement setupAssumeRole subroutine

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

* Implement Create User w/ all IAM APIs
* Call AssumeRoleBackbeat to get temporary credentials
* Call IAM Create User
* Call IAM Get User Policy if exists
* If Policy does not exist, Create User Policy
* Create Access key for the user
* Implemented Create User Test cases

feature:S3C-3532 Create user Implementation

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
pmd-rules.xml

This PR will implement OSIS list users using Vault IAM `list-users`.
* The OSIS `list-users` API can be called with following parameters:
* offset: The start index of tenants to return (optional)
* limit: The maximum number of tenants to return (optional)
* IAM `list-users` api will be called using assumed role credentials.
* If `offset` is present in the request, return the IAM `list-users` result by providing the `offset` value as the `marker` parameter.

feature:S3C-3537 Implement list users

---

build.gradle
osis-core/src/main/java/com/scality/osis/configuration/SpringRedisConfig.java
osis-core/src/main/java/com/scality/osis/redis/service/IRedisRepository.java
osis-core/src/main/java/com/scality/osis/redis/service/ScalityRedisRepository.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/ScalityAppEnvTest.java
osis-core/src/test/java/com/scality/osis/redis/service/ScalityRedisRepositoryTest.java
src/main/resources/application.properties

1. Added Lettuce Redis client config to integrate Redis
2. Connecting to Redis Sentinel nodes using SSL or Default
3. Created Redis Repository class for CRUD operations on Redis Hash using serialization of an object
4. Added test cases for Redis Repo
Design PR:
#45
Design doc: https://github.com/scality/vmware-ose-scality/blob/documentation/S3C-4390-ose-design-secret-key/Design.md

feature:S3C-4407 Integrating Redis Sentinel using Lettuce Redis client

---

Design.md
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/main/java/com/scality/osis/utils/ScalityUtils.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTenantTests.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java
osis-core/src/test/java/com/scality/osis/utils/ScalityUtilsTest.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/VaultAdmin.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/impl/VaultAdminImpl.java

Description:
Support S3 objects synchronization with changes from other sources (S3 browser, CLI).
Logic:
1. `CreateUser` stores `canonicalID` in user path
2. `listUsers`,`queryUsers`,`getUser` returns canonicalID from user path
3. `queryTenant`: if cdTenantID is not UUID  call getAccount
4. `queryUser`: if cdTenantID is not an UUID skip getAccountID

improvement:S3C-4510 Support S3 objects sync

---

osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java

Description:
As user which is not created by OSIS will not have `name` in the `path`, defaulting the value to a `Non OSIS User` string.

bugfix:S3C-4487 Non osis user returned in `listUsers`

---

Design.md
docs/api-compatibility-matrix.md
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java

Logic:
1. The `get-account` API will be called using vaultclient with the provided `canonical-id` and account details will be used to fill tenant details of the response.
1. The `list-users` API will be called with `offset` as 0 and `limit` as 1000 and the last user values in the response will be used to fill the user details of the response.
* _`canonical-id` in Scality is defined with respect to an account and any specific user cannot be retrieved using only the `canonicalID`_
* `get-user-with-canonical-id` API will be called by OSE only when user APIs does not return the `canonical-id` for any user.

feature:OSIS-1 get-user using canonicalID

---

Design.md
docs/api-compatibility-matrix.md
osis-app/src/main/java/com/scality/osis/resource/ScalityOsisController.java
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/main/java/com/scality/osis/service/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java

Description:
* Re-structuring REST Controller to modify the implementation logic with same API signatures
*  Update design for `getS3Credentials`
* Implement `getS3Credentials`
* Logic:
* Call `list-access-keys` with provided tenantId, userID
* Filter the `access-key` with provided accesskey value
* Extract the secret key for the given accesskey from REDIS and decrypt it
* If no secret key present in REDIS, return "Not Available" string for secret key
* Implement `getS3Credentials` test cases
**_Note to reviewer:_**
* _As per the Vmware’s [documentation](https://code.vmware.com/apis/1034#/required/getCredential), `tenantID` and `userID` will always present in the request and it is the platform implementation choice to use them or not._
* _As the original code has copyright and two `REST …

feature:OSIS-5 Get S3 Credentials

---

build.gradle
osis-app/src/main/java/com/scality/osis/healthcheck/VaultHealthIndicator.java
osis-core/src/main/java/com/scality/osis/ScalityAppEnv.java
osis-core/src/main/java/com/scality/osis/security/config/ScalityOsisBasicWebSecurityConfigurerAdapter.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
src/main/resources/application.properties

**Description:**
* Enable Springboot Actuator
* Enable Healthcheck endpoint of actuator
* Allow healthcheck API with no Auth headers
* Allow Actuator loggers functionality with Auth
* Add and disable metrics, threaddump
Health check Endpoint will be `https://{OSIS_URL}/_/healthcheck`
**Example Request and Response of Healthcheck**
Request:
```sh
curl -k --location --request GET 'https://localhost:8443/_/healthcheck'
```
Response:
```json
{
"status": "UP",
"components": {
"redis": {
"status": "UP",
"details": {
"version": "6.2.1"
}
},
"vault": {
"status": "UP"
}
}
}
```

feature:OSIS-3 Enable Springboot Actuator for healthcheck

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java

`query-users` API has some parameters missing in the `filter`
1. Add filter param `username`
2. Add filter param `cd_user_id`
3. Add filter param `user_id`

Improvement: OSIS-29 query users more filter params

---

vault-admin-client/src/main/java/com/scality/osis/security/crypto/AES256GCM.java
vault-admin-client/src/main/java/com/scality/osis/security/crypto/model/EncryptedAdminCredentials.java
vault-admin-client/src/main/java/com/scality/osis/security/utils/SecurityConstants.java
vault-admin-client/src/main/java/com/scality/osis/vaultadmin/utils/VaultAdminUtils.java
vault-admin-client/src/test/java/com/scality/osis/security/crypto/AES256GCMTest.java

Description:
OSIS decrypts vault admin file to extract SK. When multiple admin files exist, encrypted file will have both keys. This commit fixes by verifying decrypted value

bugfix:OSIS-33 Support multiple admin files

---

README.md
build.gradle

This PR is in response to [CVES-113](https://scality.atlassian.net/browse/CVES-113) for [CVE-2020-1938](https://nvd.nist.gov/vuln/detail/CVE-2020-1938)
[Commit # 1](https://github.com/scality/osis/commit/f9008236917f886e55d19b730b1b7a1f1574e704)
- This commit adds the dependency checker plugin, later it will be enabled in the CI
- Dependency-Check is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project’s dependencies. It does this by determining if there is a Common Platform Enumeration (CPE) identifier for a given dependency. If found, it will generate a report linking to the associated CVE entries.
- OWASP dependency-check gradle plugin is a software composition analysis tool used to find known vulnerable …

improvement: OSIS-45-fix CVE-2020-1938

---

build.gradle

- Update to next minor version (v42.2.13 -> v42.2.25) for package org.postgresql:postgresql
- change log: https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.25
After change:
```
❯ trivy image registry.scality.com/osis-dev/osis:b22d2fc2e3 | grep 21724
2022-07-04T14:35:26.458+0200	INFO	Vulnerability scanning is enabled
2022-07-04T14:35:26.458+0200	INFO	Secret scanning is enabled
2022-07-04T14:35:26.458+0200	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-04T14:35:26.458+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.1/docs/secret/scanning/#recommendation for faster secret detection
2022-07-04T14:35:48.616+0200	INFO	Detected OS: alpine
2022-07-04T14:35:48.616+0200	INFO	Detecting Alpine …
```

bugfix: OSIS-54-CVE-2022-21724

---

build.gradle
osis-app/build.gradle
osis-core/build.gradle
osis-core/src/main/java/com/scality/osis/configuration/DocumentationConfig.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java
storage-platform-clients/build.gradle

removed version definition from each project file, but configure it [here](https://github.com/scality/osis/pull/101/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R102) for all projects
so that whenever we need to bump a version, no need to change the version everywhere

feature: OSIS-67 release 1.1.0

---

osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
osis-core/src/test/java/com/scality/osis/utils/ScalityTestUtils.java

missing cd_tenant_id in the returning OsisCredential instance for GetCredential API
after fixing this, we should be able to release [this part from Integrantion CI ](https://github.com/scality/Integration/blob/development/9.1/genericStaas/env/run_osis_tests.bash#L101)

feature: OSIS-86 return cd_tenant_id in getCredential

---

osis-app/src/main/java/com/scality/osis/resource/ScalityOsisController.java
osis-core/src/main/java/com/scality/osis/model/AnonymousUser.java
osis-core/src/main/java/com/scality/osis/service/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceUserTests.java

this API is needed for OSE healthcheck route `/api/v1/core` 
after implementing this API, now the response of `https://192.168.198.12/api/v1/core` is like:
```
{
"name": "Cloud Director Object Storage Extension",
"description": "Object Storage Extension for VMware Cloud Director",
"version": "2.1.1-19362139",
"buildDate": "2022-02-15T10:24:38.725+00:00"
}
```

feature: OSIS-88 getAnonymousUser

---

Design.md
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/utils/ScalityModelConverterTest.java
storage-platform-clients/src/test/java/com/scality/osis/vaultadmin/impl/VaultAdminImplTest.java

Functionality change.
Now we list accounts which are not created through VCD as well.

feature: OSIS-70-remove-filterKey-list-accounts-parameter

---

osis-core/src/main/java/com/scality/osis/model/Information.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceMiscTests.java

This new property will tell VMWare OSE that OSIS adapter supports
standard IAM authentication.

feature: OSIS-138-iam-support-osis-spec

---

osis-core/src/main/java/com/scality/osis/service/ScalityOsisService.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTenantTests.java

Changed responses for HEAD tenant API to 200 OK for successful queries and 404 Not Found for unsuccessful queries
Reference: https://developer.vmware.com/apis/1034#/tenant/headTenant
Current open API spec of HeadTenant API from VMware
```
paths:
"/api/v1/tenants/{tenantId}":
head:
tags:
- tenant
- required
summary: Check whether the tenant exists
operationId: headTenant
description: |
Operation ID: headTenant<br>
Check whether the tenant exists
parameters:
- in: path
name: tenantId
required: true
description: Tenant ID to check on the platform
schema:
type: string
responses:
"200":
description: The tenant exists
"404":
description: "The tenant doesn't exist"
```
Note to reviewers:
- tested with Vmware Vault and swagger spec from VMware

OSIS-99 changes responses for HeadTenant API

---

build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceTenantTests.java

This version of vaultlclient-java allows empty custom attributes to be passed via PatchTenant API  for UpdateAccountAttribute calls.
2nd commit ensures consistency of tenant ID and tenant Name for a bug in OSE where the PatchTenant request from VCD OSE can have name and ID of different storage accounts.

OSIS-134 update-vaultclient-java-to-v1.1.0-and parameters-consistency-for update-tenant

---

osis-core/src/main/java/com/scality/osis/model/OsisTenant.java
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityModelConverter.java
osis-core/src/test/java/com/scality/osis/service/impl/BaseOsisServiceTest.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceMiscTests.java

Use Canonical ID for ownership of buckets as VMware now supports true IAM with OSIS 2.2.0.1

OSIS-137 add canonical ID as owner of buckets

---

.github/workflows/codeql.yaml
.github/workflows/dependency-review.yaml
.github/workflows/docker-build.yml
.github/workflows/gradle-build-and-upload.yml
.github/workflows/release.yml
.github/workflows/security.yaml
.github/workflows/test-and-build.yml
README.md
docs/RELEASE.md
docs/milestone-2-steps.md

- Migrate to ghcr
- Bump github actions
Issue: OSIS-146

Migrate to ghcr

---

build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceCredentialsTests.java

**Context:** VMware needs secret keys to be available on-demand which is contrary to AWS standard where secret keys are only shown at creation time. To achieve this OSIS stores any created access keys via OSIS in redis in AWS GCM in encrypted format. 
**Issue:** Due to [S3C-7645](https://scality.atlassian.net/browse/S3C-7645)  not being done, [an issue](https://scality.atlassian.net/browse/S3C-7406) occurs when doing a rolling deployment with new nodes on a cluster where OSIS is already enabled. This issue makes VMware cloud director UI un-usable by the end users.
The **resolution/changes** per discussion with product/customer/CS and Accounts team
This adds the capability of handling decryption failures for secret key data stored in Redis Sentinel using the method `retrieveSecretKey` used …

Improvement: osis 147 stop osis failure on decryption

---

.github/CODEOWNERS
build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceCredentialsTests.java

We need this in 7.10.9 as well now so cherry picking from https://github.com/scality/osis/pull/141
I also changed the codeowners to match that of main
- Removed user not part of scality 
- Changed mandatory review from Object Squad leads to object Squad

Improvement/osis 147 stop osis failure on decryption 7.10

---

.github/workflows/codeql.yaml
.github/workflows/dependency-review.yaml
.github/workflows/security.yaml

Adds development/2.1 used for RING 7.10.9 to workflows in the main as well.
Synthetic change for consistency, as development/2.1 already has the branch.

VAULT-150: Add-S3C-7.10.9-branch-development/2.1-to-workflows

---

build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceMiscTests.java

We are changing the error to comply with the API change. This was always the intent, but we had to rely on what was supported back then (I guess)
For S3C 9.3.0.X, 9.4
Main ticket: https://scality.atlassian.net/browse/S3C-8939

Bugfix: OSIS-149 | Update error expectation from Assume Role Backbeat API and bump OSIS to 2.2.4

---

build.gradle
osis-core/src/main/java/com/scality/osis/service/impl/ScalityOsisServiceImpl.java
osis-core/src/main/java/com/scality/osis/utils/ScalityConstants.java
osis-core/src/test/java/com/scality/osis/service/impl/ScalityOsisServiceMiscTests.java

Cherry-picked from : https://github.com/scality/osis/pull/145/commits
For S3C 7.10.9
Main ticket: https://scality.atlassian.net/browse/S3C-8939

[Cherry-pick] Bugfix: OSIS-149 | Update error expectation from Assume Role Backbeat API and bump OSIS to 2.1.5
